name: Call Deploy Action

on:
  push:
    branches:
      - main

jobs:
  Layer_deploy:
    strategy:
      matrix:
        layer: [pynacl_layer, common_layer, requests_layer]
        include:
          - layer: pynacl_layer
            path: ./layers/pynacl
          - layer: common_layer
            path: ./layers/common
          - layer: requests_layer
            path: ./layers/requests

    uses: junah201/Chizz-Bot/.github/workflows/layer.yml@main
    with:
      file_path: ${{ matrix.path }}
      layer_name: ${{ matrix.layer }}
    secrets: inherit

  Lambda_deploy:
    strategy:
      matrix:
        lambda: [event_handler, live_check]
        include:
          - lambda: event_handler
            path: ./lambdas/event_handler
          - lambda: live_check
            path: ./lambdas/live_check

    uses: junah201/Chizz-Bot/.github/workflows/lambda.yml@main
    with:
      file_path: ${{ matrix.path }}
      lambda_name: ${{ matrix.lambda }}
    secrets: inherit
