name: Call Deploy Action

on:
  push:
    branches:
      - main

jobs:
  Layer_deploy:
    strategy:
      matrix:
        layer: [pynacl_layer, common_layer, requests_layer]
        include:
          - layer: pynacl_layer
            path: ./layers/pynacl
          - layer: common_layer
            path: ./layers/common
          - layer: requests_layer
            path: ./layers/requests

    uses: junah201/chzzk-discord-bot/.github/workflows/layer.yml@main
    with:
      file_path: ${{ matrix.path }}
      layer_name: ${{ matrix.layer }}
    secrets: inherit

  Lambda_deploy:
    strategy:
      matrix:
        lambda:
          [
            event_handler,
            live_check,
            discord_oauth2_redirect,
            discord_me,
            discord_guilds,
            get_guild_channels,
            post_notification,
            get_notification_by_guild_id,
            delete_notification,
            send_test_notification,
            update_notification,
          ]
        include:
          - lambda: event_handler
            path: ./lambdas/event_handler
          - lambda: live_check
            path: ./lambdas/live_check
          - lambda: discord_oauth2_redirect
            path: ./lambdas/discord_oauth2_redirect
          - lambda: discord_me
            path: ./lambdas/discord_me
          - lambda: discord_guilds
            path: ./lambdas/discord_guilds
          - lambda: get_guild_channels
            path: ./lambdas/get_guild_channels
          - lambda: post_notification
            path: ./lambdas/post_notification
          - lambda: get_notification_by_guild_id
            path: ./lambdas/get_notification_by_guild_id
          - lambda: delete_notification
            path: ./lambdas/delete_notification
          - lambda: send_test_notification
            path: ./lambdas/send_test_notification
          - lambda: update_notification
            path: ./lambdas/update_notification

    uses: junah201/chzzk-discord-bot/.github/workflows/lambda.yml@main
    with:
      file_path: ${{ matrix.path }}
      lambda_name: ${{ matrix.lambda }}
    secrets: inherit
